Repository AndrGab/medirepoWeb, pull requests merged in 2022-10, with the labels that each got.

#23 fix: read.me update
  README.md
  src/services/Api.js
Labels: hacktoberfest-accepted

#28 Update README.md
  README.md
Labels: hacktoberfest-accepted

#29 Fix formatting
  .env-sample
  README.md
  src/App.js
  src/App.test.js
  src/Routes.js
  src/context/ThemeContext.js
  src/context/UserContext.js
  src/index.js
  src/pages/components/AppBarMediRepo.js
  src/pages/hospitals/FastLogin.js
  src/pages/hospitals/Layout.js
  src/pages/hospitals/Login.js
  src/pages/hospitals/Register.js
  src/pages/hospitals/ResetToken.js
  src/pages/patients/Bulletin.js
  src/pages/patients/Login.js
  src/reportWebVitals.js
  src/services/Api.js
  src/setupTests.js
Labels: hacktoberfest-accepted

#30 fix repo name
  README.md
Labels: hacktoberfest-accepted

#31 fix repo name
  README.md
Labels: hacktoberfest-accepted

#32 added i18n and fix backend
  package.json
  src/i18n.js
  src/index.js
  src/pages/components/AppBarMediRepo.js
  src/pages/hospitals/FastLogin.js
  src/pages/hospitals/Layout.js
  src/pages/hospitals/Login.js
  src/pages/hospitals/Register.js
  src/pages/hospitals/ResetToken.js
  src/pages/hospitals/app/Account.js
  src/pages/hospitals/app/Bulletin.js
  src/pages/hospitals/app/Dashboard.js
  src/pages/hospitals/app/Settings.js
  src/pages/hospitals/app/components/BulletinAdd.js
  src/pages/hospitals/app/components/BulletinDelete.js
  src/pages/hospitals/app/components/BulletinView.js
  src/pages/hospitals/app/components/CustomToolbarAdd.js
  src/pages/hospitals/app/hooks/useBulletinsList.js
  src/pages/hospitals/app/hooks/useHospitalList.js
  src/pages/patients/Bulletin.js
  src/pages/patients/Login.js
Labels: hacktoberfest-accepted

#34 portuguese removed
  README.md
Labels: hacktoberfest-accepted

#41 Added Spanish (es) translation
  src/i18n.js
Labels: hacktoberfest-accepted

#38 Added French translations in `i18n.js`.
  src/i18n.js
Labels: hacktoberfest-accepted

#42 feat: browser language detector
  src/i18n.js
Labels: hacktoberfest-accepted

#43 fallback lang
  src/i18n.js
Labels: hacktoberfest-accepted

#47 fix: use of translation
  src/pages/hospitals/Login.js
Labels: hacktoberfest-accepted

#49 Update i18n.js
  src/i18n.js
Labels: hacktoberfest-accepted

#48 Add polish translation
  src/i18n.js
Labels: hacktoberfest-accepted

#52 Hacktoberfest 2022
  README.md
Labels: hacktoberfest-accepted

#53 add Indonesian
  src/i18n.js
Labels: hacktoberfest-accepted

#54 Login Icon used instead of Login
  src/pages/hospitals/FastLogin.js
  src/pages/hospitals/Login.js
  src/pages/hospitals/Register.js
  src/pages/patients/Login.js
Labels: hacktoberfest-accepted

#62 Fixed the favicon issue
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
Labels: hacktoberfest-accepted

#63 Added Contributing.md
  Contributing.md
Labels: hacktoberfest-accepted

#59 Added disable logic to download csv button
  src/pages/hospitals/app/Bulletin.js
Labels: hacktoberfest-accepted

#64 Add German translation
  src/i18n.js
Labels: hacktoberfest-accepted

#58 Add language switch button
  src/i18n.js
  src/index.js
  src/pages/components/AppBarMediRepo.js
Labels: hacktoberfest-accepted

#65 Fixes French translations in i18n.js
  src/i18n.js
Labels: hacktoberfest-accepted

#72 Added loader on accounts page
  src/pages/hospitals/app/Account.js
Labels: hacktoberfest-accepted

#73 Update i18n.js
  src/i18n.js
Labels: hacktoberfest-accepted

#74 pa-IN (punjabi) translations added
  src/i18n.js
Labels: hacktoberfest-accepted

#69 translated to hindi
  src/i18n.js
Labels: hacktoberfest-accepted

#75 Split locales
  src/i18n.js
  src/locales/cn/content.json
  src/locales/de/content.json
  src/locales/en/content.json
  src/locales/es/content.json
  src/locales/fi/content.json
  src/locales/fr/content.json
  src/locales/hi/content.json
  src/locales/id/content.json
  src/locales/mr/content.json
  src/locales/pa/content.json
  src/locales/pl/content.json
  src/locales/pt/content.json
  src/locales/ta/content.json
  src/pages/components/AppBarMediRepo.js
  src/pages/hospitals/FastLogin.js
  src/pages/hospitals/Login.js
  src/pages/hospitals/Register.js
  src/pages/patients/Login.js
Labels: hacktoberfest-accepted

#79 Added Bengali language
  src/i18n.js
  src/locales/bn/content.json
Labels: hacktoberfest-accepted

#83 Create content.json with Gujarati Language
  src/locales/gu/content.json
Labels: hacktoberfest-accepted

#84 Update i18n.js
  src/i18n.js
Labels: hacktoberfest-accepted

#88 Add semantic heading to Login page
  src/pages/patients/Login.js
Labels: hacktoberfest-accepted

#91 Added Telugu translation to i18n
  src/i18n.js
  src/locales/te/content.json
Labels: hacktoberfest-accepted

#93 Fix and improve Finnish translation
  src/locales/fi/content.json
Labels: hacktoberfest

#95 fix: add SPA behavior
  src/components/RouterLink/RouterLink.js
  src/pages/NotFound.js
  src/pages/hospitals/Login.js
  src/pages/hospitals/Register.js
  src/pages/hospitals/ResetToken.js
  src/pages/patients/Login.js
Labels: hacktoberfest-accepted

#101 Feature: A new modal window for changing languages [fixes #96]
  .env
  src/pages/components/AppBarMediRepo.js
  src/pages/components/TranslateModal.js
Labels: hacktoberfest-accepted

#106 🌴 Added malayalam
  .gitignore
  src/i18n.js
  src/locales/ml/content.json
Labels: hacktoberfest-accepted

#110 added Hebrew language
  src/i18n.js
  src/locales/he/content.json
Labels: hacktoberfest-accepted

#112 Dutch translations
  src/i18n.js
  src/locales/nl/content.json
Labels: hacktoberfest-accepted

#115 Add Samoan(sm) language
  src/i18n.js
  src/locales/sm/content.json
Labels: hacktoberfest-accepted

#117 Added Assamese(as) language support
  src/i18n.js
  src/locales/as/content.json
Labels: hacktoberfest-accepted

#121 🐛 Bugfix: modal window size #97
  src/pages/hospitals/app/Bulletin.js
Labels: hacktoberfest-accepted

#120 Typo fixes in feature request template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: hacktoberfest-accepted

#119 feat: add urdu language
  src/i18n.js
  src/locales/ur/content.json
Labels: hacktoberfest-accepted

#118 Hausa
  src/i18n.js
  src/locales/ha/content.json
Labels: hacktoberfest-accepted

#129 Added Vietnamese Translations
  src/i18n.js
  src/locales/vi/content.json
Labels: hacktoberfest-accepted

#134 Added Slovenian Language Support
  src/i18n.js
  src/locales/sl/content.json
Labels: hacktoberfest-accepted

#131 Translated to Maithili language
  src/i18n.js
  src/locales/ma/content.json
Labels: hacktoberfest, hacktoberfest-accepted

#133 updated src/i18n.js file for chinese language
  src/i18n.js
  src/locales/zh_CN/content.json
Labels: hacktoberfest-accepted

#138 Add asterisk mark in required fields in medical report form
  src/pages/hospitals/app/components/BulletinAdd.js
Labels: hacktoberfest-accepted

#137 Add required asterisk(*) mark in hospital input in login form
  src/pages/patients/Login.js
Labels: hacktoberfest-accepted

#140 Update content.json
  src/locales/gu/content.json
Labels: hacktoberfest-accepted

#139 Nepali Local: correcting local words
  src/locales/np/content.json
Labels: hacktoberfest-accepted

#145 Update content.json
  src/locales/fr/content.json
Labels: hacktoberfest-accepted

#147 Added Russian translation
  src/i18n.js
  src/locales/ru/content.json
Labels: hacktoberfest-accepted
